global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: case-management
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          service: case-management
          env: dev

  - job_name: transaction-monitoring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
        labels:
          service: transaction-monitoring
          env: dev

  - job_name: customer-kyc
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8082
        labels:
          service: customer-kyc
          env: dev
