spring:
  application:
    name: remediation-engine
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: aiops-remediation-engine
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.yourbank.aiops.remediation.application.RemediationDecision

server:
  port: 9004

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

aiops:
  remediation:
    namespace:
      aml:   ${AML_NAMESPACE:aml}
      aiops: ${AIOPS_NAMESPACE:aiops}
    scale-out-replicas: ${SCALE_OUT_REPLICAS:2}

logging:
  level:
    com.yourbank.aiops: INFO
    io.fabric8: WARN
    org.springframework.kafka: WARN
