apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: aiops
  labels:
    app: agent-service
spec:
  type: NodePort
  selector:
    app: agent-service
  ports:
    - name: http
      port: 9007
      targetPort: http
      nodePort: 30907
